services:
  - type: web
    name: horilla
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn dj-database-url psycopg2-binary
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn horilla.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: horilla-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.10.0
